keys:
  - &silas_mifla age1xx7h8mrp5v9dy2zmsnc78whqa2zct85cga9w0nq29rhcxcfwlyzs5h5644
  - &silas_nixnook age1v5stjx347ljd966j0svxrvfm5r8u7wnslfj3q6xxd89w5p5ycv7qskt0zg
creation_rules:
  - key_groups:
    - age:
      - *silas_mifla
      - *silas_nixnook
