name: Publish

on:
  push:
    tags:
      - 'v*'
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: ^7.18.0
      - run: pnpm ci:publish
